on: 
  push:
    branches:
      - main
      - dev
      - feature/*
    paths:
      - "src/**"
  pull_request:
    branches:
      - main
      - dev
      - feature/*

jobs:
  tesst:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      
      - name: Run tests
        run: |
          echo "Running tests..."
          npm test
    